language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
  - develop
notifications:
  email:
    recipients:
    - boy_carlos_eduardo@hotmail.com
services:
- mysql
before_install:
- mysql -e 'CREATE DATABASE IF NOT EXISTS forge;'
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent --settings settings.xml
- mvn sonar:sonar -Dsonar.organization=c1e1s1t-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR --settings settings.xml
